version: "3.9"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  webapp:
    restart: always
    build: .
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations --noinput && 
      python manage.py migrate
      && daphne -b 0.0.0.0 -p 8000 chat.asgi:application"


  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - webapp


volumes:
  static_volume:
  media_volume: