# Generated by Django 4.0.6 on 2022-07-28 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_rating', to='chat_support.chatmessage', verbose_name='сообщение, которое оцениваем'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rating', to=settings.AUTH_USER_MODEL, verbose_name='кем поизведена оценка'),
        ),
    ]
