# Generated by Django 4.0.6 on 2022-08-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='is_active',
            new_name='is_actives',
        ),
    ]
