# Generated by Django 4.0.6 on 2022-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0002_alter_chatmessage_author_alter_rating_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
