# Generated by Django 4.0.6 on 2022-08-29 11:38

import chat_support.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0002_rename_is_active_rating_is_actives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_messages', to='chat_support.chatdialog', verbose_name='диалог'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='chat_support.chatdialog', verbose_name='диалог, который оцениваем'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=13, unique=True, validators=[chat_support.validator.username_validator], verbose_name='табельный номер'),
        ),
    ]
