# Generated by Django 4.0.6 on 2022-08-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0003_rating_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdialog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
